tablero3EnRaya1=[
    ['X','X','O']
    ['','X','O']
    ['','','O']
]
tablero3EnRaya2=[
    ['X','O','X']
    ['0','X','O']
    ['0','X','O']
]
tablero3EnRaya3=[
    ['X','X','0']
    ['0','X','X']
    ['0','0','X']
]